#!/bin/bash
#
# From https://github.com/holman/dotfiles/blob/master/bin/battery-status
# Thanks holman <3
#
# battery-status
#
# A quick little indicator for battery status on your Mac laptop, suitable for
# display in your prompt.

battstat=$(pmset -g batt)
time_left=$(echo $battstat |
  tail -1 |
  cut -f2 |
  awk -F"; " '{print $3}' |
  cut -d' ' -f1
)

if [[ $(pmset -g ac) == *"No adapter attached."* ]]
then
  emoji='🔋'
else
  emoji='🔌'
fi

if [[ $time_left == *"(no"* || $time_left == *"not"* || $time_left == *"0:00"* ]]
then
  time_left=''
fi

if [[ $time_left != '' ]]
then
  time_left=$(echo " $time_left")
fi

printf "\033[1;92m$emoji $time_left \033[0m"
