#!/usr/bin/env bash
#
# Run all dotfiles installers.
# Stolen from https://github.com/holman/dotfiles/blob/master/script/install, thanks 😘

set -e

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
