#!/usr/bin/env bash
#
# Run all dotfiles installers.
# Stolen from https://github.com/holman/dotfiles/blob/master/script/install, thanks 😘

set -e

# gitconfig
echo "🍰  updating gitconfig..."
cp ./git/.gitconfig ~/.gitconfig
git config --global credential.helper osxkeychain

# find the installers and run them iteratively
realpath() {
    [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

for src in $(find -H . -maxdepth 4 -name install.sh | sed 's|/[^/]*$||')
do
  (
  file=`realpath $src`
  echo "⛑  installing $file..."
  cd $file
  sh install.sh
  echo "   done!"
  )
done

echo "🍰  getting xcode dev tools..."
xcode-select --install

echo "🍰  doing a ruby dance..."
gem install jekyll
